version: "3.7"
services:
    cdk:
        container_name: tsdat-cdk
        hostname: tsdat-cdk
        image: tsdat-cdk
        build: .
        command: ['tail', '-f',  '/dev/null']
        volumes:
            - ./:/root/cdk_app
            - ../tsdat:/root/tsdat
            - ../pipeline-template:/root/pipeline-template
            - ${HOME}/.aws:/root/.aws
        environment:
            - PYTHONPATH:/root/tsdat:/root/pipeline-template:/root/cdk_app/

