# This file configures all pipelines to be deployed on AWS.

###################################################################
# Build Parameters
###################################################################
# GitHub Repository
github_org: a2edap
pipelines_repo: buoy-pipelines
aws_build_repo: buoy-deploy

# AWS Information
account_id: 332883119153
region: us-west-2
vpc_id: vpc-09ed7a9059ac5e392

# Create a CodeStar connection to allow AWS to have access to your GitHub repositories
# https://docs.aws.amazon.com/dtconsole/latest/userguide/connections-create-github.html
github_codestar_arn: FILL_ME_IN  

# Bucket names - must be unique across AWS!
# Bucket names must be DNS-compliant. This means they should not contain underscores, end with a dash, have consecutive periods, or use dashes adjacent to periods.
input_bucket_name: buoy-raw-data
output_bucket_name: buoy-output

###################################################################
# Array of pipelines.  Each pipeline has the following properties:
# 
#   name -      Name of the pipeline.  Name will be used to create sns
#               topic.
#  
#   type -      Ingest or VAP
# 
#   input_dir - Path where input files for this pipeline will be 
#               uploaded. Path is relative to input bucket.
#               Only used for Ingest pipelines.
#  
#   config_file_path - Relative path from the pipelines_repository
#                      where the Tsdat pipeline config file is
#                      located
#
#   trigger -   What will trigger the pipelien.  Can be S3 or cron.
#               S3 means a trigger from new files in the input
#               bucket.  Cron means a trigger from a cron scheduled
#               lambda.  Most of the time, Ingest pipelines will
#               use S3, but they can use cron if multiple files
#               need to be processed together.  VAP pipelines
#               must always use cron.
#
#  schedule -   Schedule for cron triggers.  Can be hourly, daily,
#               weekly, or monthly.  Only used if trigger is cron.
###################################################################
pipelines_to_deploy:
 - name: lidar_humboldt
   type: Ingest
   input_dir: lidar/humboldt
   config_file_path: pipelines/lidar/config/pipeline_humboldt.yaml
   trigger: S3

 - name: lidar_morro
   type: Ingest
   input_dir: lidar/morro
   config_file_path: pipelines/lidar/config/pipeline_morro.yaml
   trigger: S3

 - name: vap1_humboldt
   type: VAP
   config_file_path: pipelines/lidar/config/pipeline_morro.yaml
   trigger: cron
   schedule: daily
