# This file configures all pipelines to be deployed on AWS.

###################################################################
# Build Parameters
###################################################################
# GitHub Repository (TODO: support repos being in 2 different orgs)
github_org: carinatest
pipelines_repo_name: ingest-buoy
aws_repo_name: aws-template

# AWS Information
account_id: "332883119153"
region: us-west-2

# Create a CodeStar connection to allow AWS to have access to your GitHub repositories
# https://docs.aws.amazon.com/dtconsole/latest/userguide/connections-create-github.html#connections-create-github-console
github_codestar_arn: arn:aws:codestar-connections:us-east-2:332883119153:connection/817c8dda-0547-4429-9fa9-88afde4fad58

###################################################################
# Array of pipelines.  Each pipeline has the following properties:
#
#   name -      Name of the pipeline.
#
#   location -  Location where this pipeline runs.  $name_$location
#               will be used to name several AWS resources.
#
#   type -      Ingest or VAP
#
#   config_file_path - Relative path from the pipelines_repository
#                      where the Tsdat pipeline config file is
#                      located
#
#   trigger -   What will trigger the pipelien.  Can be S3 or Cron.
#               S3 means a trigger from new files in the input
#               bucket.  Cron means a trigger from a cron scheduled
#               lambda.  Most of the time, Ingest pipelines will
#               use S3, but they can use cron if multiple files
#               need to be processed together.  VAP pipelines
#               must always use cron.
#
#   input_prefix - Relative path from the root of the input S3 bucket
#                  where input files for this pipeline will be
#                  uploaded. Only used for Ingest pipelines.
#
#  schedule -   Schedule for cron triggers.  Can be Hourly, Daily,
#               Weekly, or Monthly.  Only used if trigger is cron.
#
#  TODO:        We may want to add paramters for lambda timeout and
#               memory if we need to customize them per pipeline
###################################################################
pipelines_to_deploy:
  - name: lidar
    location: humbolt
    type: Ingest
    config_file_path: pipelines/lidar/config/pipeline_humboldt.yaml
    trigger: S3
    input_prefix: lidar/humboldt

  - name: lidar
    location: morro
    type: Ingest
    config_file_path: pipelines/lidar/config/pipeline_morro.yaml
    trigger: S3
    input_prefix: lidar/morro

  # - name: vap1
  #   location: morro
  #   type: VAP
  #   config_file_path: pipelines/lidar/config/pipeline_morro.yaml
  #   trigger: Cron
  #   schedule: Daily
